export const VACATION_REQUEST_STATUSES = [
  "draft",
  "submitted",
  "under_review",
  "pending_manager_approval",
  "pending_hr_approval",
  "approved",
  "rejected",
  "cancelled",
  "returned_for_changes",
  "scheduled",
  "consumed",
  "expired",
];

export const vacationPolicySchema = {
  id: "",
  policyCode: "",
  version: 1,
  versionLabel: "",
  effectiveFrom: "",
  effectiveTo: "",
  countryCode: "",
  companyId: "",
  companyName: "",
  locationId: "",
  locationName: "",
  employeeCategory: "all",
  leaveType: "annual",
  entitlementDays: 18,
  minServiceMonths: 3,
  allowNegativeBalance: false,
  negativeBalanceLimit: 0,
  accrualMode: "annual",
  carryOverLimit: 5,
  expiresAfterMonths: 12,
  excludeWeekends: true,
  excludeHolidays: true,
  requestLeadDays: 7,
  bookingWindowMonths: 12,
  hrApprovalThresholdDays: 5,
  minCoverageRatio: 0.65,
  allowDelegation: true,
  outsidePeriodPolicy: "restricted",
  multipleActiveAllowed: true,
  maxDaysPerRequest: 15,
  planningRequired: true,
  restrictHighSeason: false,
  highSeasonMonths: [],
  allowedAccumulationPeriods: 2,
  policyFamily: "annual-leave",
  status: "active",
};

export default vacationPolicySchema;
