export const vacationRequestSchema = {
  id: "",
  employeeId: "",
  employeeName: "",
  companyId: "",
  company: "",
  location: "",
  department: "",
  employeeCategory: "",
  manager: "",
  leaveType: "annual",
  status: "draft",
  requestedBy: "",
  requestedAt: "",
  startDate: "",
  endDate: "",
  requestMode: "standard",
  segments: [],
  retroactive: false,
  parentRequestId: "",
  accumulatedPeriods: 1,
  requestedDays: 0,
  chargeableDays: 0,
  holidaysExcluded: 0,
  weekendsExcluded: 0,
  balanceImpactDays: 0,
  policyId: "",
  policyName: "",
  note: "",
  rejectionReason: "",
  returnReason: "",
  currentStepId: "",
  currentApprover: "",
  detailStatus: "on_time",
};

export default vacationRequestSchema;
