const employeesCopy = {
  es: {
    language: "es",
    locale: "es-BO",
    common: {
      noDate: "Sin fecha",
      pending: "Pendiente",
      notDefined: "Sin definir",
      noData: "Sin dato",
      companyPending: "Compania pendiente",
      levelPending: "Nivel pendiente",
      managerPending: "Pendiente",
      noPipeline: "Sin pipeline vinculado",
      noRole: "Cargo",
      noCompany: "Empresa",
      manual: "Manual",
      yes: "Si",
      no: "No",
      noManager: "Sin manager",
      noLevel: "Sin nivel",
      noApprover: "Sin aprobador definido",
      noEmail: "Sin email registrado",
      noPhone: "Sin telefono registrado",
      noReason: "Sin motivo",
      noOwner: "Sin responsable",
      noDateRangeStart: "Sin inicio",
      noDateRangeEnd: "Sin fin",
      noBirthDate: "Sin fecha de nacimiento",
      noYear: "Sin ano",
      noInstitution: "Institucion pendiente",
      noAchievements: "Sin logros registrados.",
    },
    type: {
      remote: "Remoto",
      hybrid: "Hibrido",
      onsite: "Presencial",
    },
    status: {
      active: "Activo",
      leave: "En licencia",
      pending: "Pendiente",
      approved: "Aprobado",
      rejected: "Rechazado",
      missing: "Faltante",
      planned: "Planificado",
      completed: "Completado",
      inactive: "Inactivo",
      in_progress: "En curso",
    },
    actions: {
      openProfile360: "Ver perfil 360",
      goProfile360: "Ir al perfil 360",
      approveHire: "Aprobar alta",
      saveDocument: "Guardar documento",
      saveDependent: "Guardar dependiente",
      saveAssignment: "Guardar asignacion",
      saveStudy: "Guardar estudio",
      saveExperience: "Guardar experiencia",
      savePermission: "Guardar permiso",
      saveLeave: "Guardar licencia",
      saveSalary: "Guardar analisis salarial",
      loadDemo: "Cargar referencia",
      clearDemo: "Limpiar referencia",
      processing: "Procesando...",
      openProfile: "Abrir perfil 360",
      submitAuthorization: "Enviar a autorizacion",
    },
    header: {
      eyebrow: "Workspace de empleados",
      title: "Control integral del colaborador",
      description:
        "Opera la dotacion, centraliza nuevas altas y conecta el frente de Employees con el pipeline de Recruitment sin perder trazabilidad.",
    },
    tabs: {
      profile: "Perfil",
      documents: "Documentos",
      dependents: "Dependientes",
      assignments: "Asignaciones",
      studies: "Estudios",
      experience: "Experiencia",
      permissions: "Permisos",
      leaves: "Ausencias",
      salary: "Salario",
    },
    filters: {
      search: "Buscar",
      searchPlaceholder: "Nombre, puesto o area",
      company: "Compania",
      area: "Area",
      status: "Estado",
      location: "Ubicacion",
      allPlural: "Todas",
      allStates: "Todos",
    },
    table: {
      employee: "Colaborador",
      context: "Contexto",
      origin: "Origen",
      contract: "Contrato",
      dossier: "Expediente",
      state: "Estado",
      entry: "Ingreso",
      pipelineFree: "Ingreso sin pipeline",
      docs: "docs",
      score: "Score",
    },
    profileHero: {
      source: "Origen Recruitment",
      entry: "Ingreso",
      position: "Posicion",
      manager: "Manager",
      dossier: "Expediente",
      completion: "Completitud",
      engagement: "Engagement",
    },
    form: {
      source: "Origen",
      manualEntry: "Alta manual",
      fromRecruitment: "Desde Recruitment",
      candidate: "Candidato",
      selectCandidate: "Selecciona candidato",
      fullName: "Nombre",
      structuralPosition: "Posicion estructural",
      selectPosition: "Selecciona posicion",
      position: "Posicion",
      area: "Area",
      selectArea: "Selecciona area",
      organizationalLevel: "Nivel organizacional",
      manager: "Manager",
      location: "Ubicacion",
      selectLocation: "Selecciona ubicacion",
      contract: "Contrato",
      employeeType: "Tipo de empleado",
      email: "Email",
      entryDate: "Ingreso",
      requestedBy: "Solicitado por",
      requestedByDefault: "HR Operations",
      contractDefault: "Indefinido",
    },
    salary: {
      base: "Base",
      baseHelper: "Compensacion fija vigente",
      variable: "Variable",
      variableHelper: "Incentivo anual o variable",
      market: "Mercado",
      marketHelper: "Referencia externa",
      compaRatio: "Compa ratio",
      compaRatioHelper: "Posicion frente a banda",
    },
  },
  en: {
    language: "en",
    locale: "en-US",
    common: {
      noDate: "No date",
      pending: "Pending",
      notDefined: "Not defined",
      noData: "No data",
      companyPending: "Company pending",
      levelPending: "Level pending",
      managerPending: "Pending",
      noPipeline: "No linked pipeline",
      noRole: "Role",
      noCompany: "Company",
      manual: "Manual",
      yes: "Yes",
      no: "No",
      noManager: "No manager",
      noLevel: "No level",
      noApprover: "No approver defined",
      noEmail: "No email registered",
      noPhone: "No phone registered",
      noReason: "No reason",
      noOwner: "No owner",
      noDateRangeStart: "No start",
      noDateRangeEnd: "No end",
      noBirthDate: "No birth date",
      noYear: "No year",
      noInstitution: "Institution pending",
      noAchievements: "No achievements registered.",
    },
    type: {
      remote: "Remote",
      hybrid: "Hybrid",
      onsite: "On site",
    },
    status: {
      active: "Active",
      leave: "On leave",
      pending: "Pending",
      approved: "Approved",
      rejected: "Rejected",
      missing: "Missing",
      planned: "Planned",
      completed: "Completed",
      inactive: "Inactive",
      in_progress: "In progress",
    },
    actions: {
      openProfile360: "View 360 profile",
      goProfile360: "Go to 360 profile",
      approveHire: "Approve hire",
      saveDocument: "Save document",
      saveDependent: "Save dependent",
      saveAssignment: "Save assignment",
      saveStudy: "Save study",
      saveExperience: "Save experience",
      savePermission: "Save permission",
      saveLeave: "Save leave",
      saveSalary: "Save salary analysis",
      loadDemo: "Load reference data",
      clearDemo: "Clear reference data",
      processing: "Processing...",
      openProfile: "Open 360 profile",
      submitAuthorization: "Send for approval",
    },
    header: {
      eyebrow: "Employee Workspace",
      title: "Integrated employee control",
      description:
        "Run workforce operations, centralize new hires, and connect Employees with the Recruitment pipeline without losing traceability.",
    },
    tabs: {
      profile: "Profile",
      documents: "Documents",
      dependents: "Dependents",
      assignments: "Assignments",
      studies: "Studies",
      experience: "Experience",
      permissions: "Permissions",
      leaves: "Leaves",
      salary: "Salary",
    },
    filters: {
      search: "Search",
      searchPlaceholder: "Name, role, or area",
      company: "Company",
      area: "Area",
      status: "Status",
      location: "Location",
      allPlural: "All",
      allStates: "All",
    },
    table: {
      employee: "Employee",
      context: "Context",
      origin: "Origin",
      contract: "Contract",
      dossier: "File",
      state: "Status",
      entry: "Start",
      pipelineFree: "Hired without pipeline",
      docs: "docs",
      score: "Score",
    },
    profileHero: {
      source: "Recruitment source",
      entry: "Start date",
      position: "Position",
      manager: "Manager",
      dossier: "File",
      completion: "Completion",
      engagement: "Engagement",
    },
    form: {
      source: "Origin",
      manualEntry: "Manual hire",
      fromRecruitment: "From Recruitment",
      candidate: "Candidate",
      selectCandidate: "Select candidate",
      fullName: "Name",
      structuralPosition: "Structural position",
      selectPosition: "Select position",
      position: "Position",
      area: "Area",
      selectArea: "Select area",
      organizationalLevel: "Organizational level",
      manager: "Manager",
      location: "Location",
      selectLocation: "Select location",
      contract: "Contract",
      employeeType: "Employee type",
      email: "Email",
      entryDate: "Start date",
      requestedBy: "Requested by",
      requestedByDefault: "HR Operations",
      contractDefault: "Indefinite",
    },
    salary: {
      base: "Base",
      baseHelper: "Current fixed compensation",
      variable: "Variable",
      variableHelper: "Annual or variable incentive",
      market: "Market",
      marketHelper: "External benchmark",
      compaRatio: "Compa-ratio",
      compaRatioHelper: "Position against band",
    },
  },
};

export default employeesCopy;
